version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/docker/backend/Dockerfile
      target: prod
      args:
        - DATABASE_URL=$DATABASE_URL
        - DJANGO_SUPERUSER_EMAIL=$DJANGO_SUPERUSER_EMAIL
        - DJANGO_SUPERUSER_USERNAME=$DJANGO_SUPERUSER_USERNAME
        - DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD
    volumes:
      - static:/app/static
    ports:
      - 8000:8000
    env_file:
      - .env

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/docker/frontend/Dockerfile
      target: prod
      args:
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
    ports:
      - 3000:3000
    env_file:
      - .env

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: apps/docker/nginx/Dockerfile
    volumes:
      - static:/app/static
      - $EB_LOG_BASE_DIR/nginx/:/var/log/nginx/
    ports:
      - 80:80

volumes:
  static:
