version: "3.9"

services:
  backend:
    extends:
      file: docker-compose.yaml
      service: backend
    build:
      target: dev
    develop:
      watch:
        - action: sync
          path: apps/backend
          target: /app
        - action: rebuild
          path: apps/backend/requirements.txt

  frontend:
    extends:
      file: docker-compose.yaml
      service: frontend
    build:
      target: dev
    develop:
      watch:
        - action: sync
          path: apps/frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: apps/frontend/package.json

  nginx:
    extends:
      file: docker-compose.yaml
      service: nginx

volumes:
  static:
